<a href="https://colab.research.google.com/github/Regis-Caelum/Machine-Learning/blob/main/Bitcoin_price_predictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Description: This program predicts the price of Bitcoin for the next 30 days.

In [2]:
#import libraries
import pandas as pd
import numpy as np

In [4]:
#Load data
from google.colab import files
uploaded = files.upload()

Saving bitcoin_price_Training - Training.csv to bitcoin_price_Training - Training.csv


In [10]:
#Store the data into a variable
df = pd.read_csv('bitcoin_price_Training - Training.csv')

#Show the first 7 rows of data
df.head(7)

Date     Open     High  ...    Close         Volume      Market Cap
0  Jul 31, 2017  2763.24  2889.62  ...  2875.34    860,575,000  45,535,800,000
1  Jul 30, 2017  2724.39  2758.53  ...  2757.18    705,943,000  44,890,700,000
2  Jul 29, 2017  2807.02  2808.76  ...  2726.45    803,746,000  46,246,700,000
3  Jul 28, 2017  2679.73  2897.45  ...  2809.01  1,380,100,000  44,144,400,000
4  Jul 27, 2017  2538.71  2693.32  ...  2671.78    789,104,000  41,816,500,000
5  Jul 26, 2017  2577.77  2610.76  ...  2529.45    937,404,000  42,455,000,000
6  Jul 25, 2017  2757.50  2768.08  ...  2576.48  1,460,090,000  45,410,100,000

[7 rows x 7 columns]

In [11]:
#remove the date column
df.drop(['Date'],1,inplace=True)
df.drop(['High'],1,inplace=True)
df.drop(['Low'],1,inplace=True)
df.drop(['Volume'],1,inplace=True)
df.drop(['Market Cap'],1,inplace=True)

In [12]:
#Show the first 7 roes of new dataset
df.head(7)

Open    Close
0  2763.24  2875.34
1  2724.39  2757.18
2  2807.02  2726.45
3  2679.73  2809.01
4  2538.71  2671.78
5  2577.77  2529.45
6  2757.50  2576.48

In [14]:
#A variable for prediction n days out into future
prediction_days = 30

#Create another column shifted 'n' units up
df['Prediction'] = df[['Close']].shift(-prediction_days)

In [15]:
#Show the first 7 rows of the new dataset
df.head(7)

Open    Close  Prediction
0  2763.24  2875.34     2434.55
1  2724.39  2757.18     2480.84
2  2807.02  2726.45     2539.32
3  2679.73  2809.01     2574.79
4  2538.71  2671.78     2552.45
5  2577.77  2529.45     2478.45
6  2757.50  2576.48     2589.41

In [16]:
#Show the last 7 rows of the new dataset
df.tail(7)

Open   Close  Prediction
1549   98.10  112.50         NaN
1550  106.25   97.75         NaN
1551  116.38  105.21         NaN
1552  139.00  116.99         NaN
1553  144.00  139.00         NaN
1554  134.44  144.54         NaN
1555  135.30  134.21         NaN

In [17]:
#Create the independent dataset

#Convert the dataframe to a numpy array and the dropp the prediction column
df.drop(['Open'],1,inplace=True)
X = np.array(df.drop(['Prediction'],1))

#Remove the last 'n'roes where 'n'is the prediction_days

X = X[:len(df)-prediction_days]

print(X)

[[2875.34]
 [2757.18]
 [2726.45]
 ...
 [ 128.8 ]
 [ 132.3 ]
 [ 129.  ]]


In [23]:
#Create the dependent dataset

#Convert the dataframe to a numpy array

y = np.array(df['Prediction'])

# Get all of the vaalues except the las 'n' rows
y = y[:-prediction_days]
print(y)

[2434.55 2480.84 2539.32 ...  139.    144.54  134.21]


In [24]:
#Split the data into 80% training and 20% testing
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(X,y, test_size=0.2)

In [26]:
#Set the prediction_days_array = the last 30 rows from the original dataset
prediction_days_array = np.array(df.drop(['Prediction'],1))[-prediction_days:]
print(prediction_days_array)

[[129.75]
 [133.48]
 [131.98]
 [133.2 ]
 [126.7 ]
 [123.89]
 [122.88]
 [122.  ]
 [121.99]
 [123.5 ]
 [123.02]
 [118.76]
 [114.22]
 [111.5 ]
 [117.98]
 [115.  ]
 [115.24]
 [117.2 ]
 [112.67]
 [113.57]
 [111.5 ]
 [112.3 ]
 [115.91]
 [112.5 ]
 [ 97.75]
 [105.21]
 [116.99]
 [139.  ]
 [144.54]
 [134.21]]


In [27]:
from sklearn.svm import SVR

#Create and train the Support Vector Machine (Regression) using radial basis function
svr_rbf = SVR(kernel='rbf',C=1e3,gamma=0.00001)
svr_rbf.fit(xtrain,ytrain)

SVR(C=1000.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma=1e-05,
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [28]:
#test model
svr_rbf_confidence = svr_rbf.score(xtest, ytest)
print('accuracy: ', svr_rbf_confidence)

accuracy:  0.8394141753228669


In [29]:
#print the predicted values
svm_prediction = svr_rbf.predict(xtest)
print(svm_prediction)

print()

#print the actual values
print(ytest)

[ 617.46297029  926.25290486  654.50279093  104.35742505  452.18648255
  604.14296225  242.48669855 2420.44328741  376.79535956  401.94800811
  615.82839474  424.40959399  247.67308462  615.37580811  224.13068409
   99.51279215  490.83793716  330.38607768  109.27097466  714.0171906
  600.33318815  288.12110724  353.38799917  231.40975641  221.21583449
  673.97239275  447.0200525   114.28987006  369.40859852  124.54163525
  107.00661598  938.98599154  283.98373068  105.78511934  460.84160236
  481.34531     461.67173899  179.6336779   227.15173769  909.89288806
  260.34681326  258.86402692  192.57874143  585.3564041   621.61062641
  748.50970466  415.36752127  229.71651077 1180.57893465  356.70257648
  131.38188444  572.01465252  777.34363223  119.27833766  409.3585383
  213.45019519  241.61828601  728.50129353  595.2307164   254.88526532
 2298.44653663  953.57263668  358.41931165  593.90342176  937.8409479
  112.11825     468.10539015  764.9929205   371.19114391  241.65869226
  642.284

In [31]:
#Print the model predictions for the next 30 days
svm_prediction = svr_rbf.predict(prediction_days_array)

print(svm_prediction)

print()

#Print the actual price
print(df.tail(prediction_days))

[126.47230308 129.44215435 128.23535238 129.21563576 124.12359561
 122.02682451 121.28952249 120.65434762 120.64716879 121.74108154
 121.39119643 118.37535555 115.34686232 113.62952051 117.84107135
 115.8529996  116.0099378  117.31249789 114.35905321 114.92968814
 113.62952051 114.12683501 116.45103041 114.25218557 106.17379981
 109.95493813 117.17117405 134.01979304 138.81290857 130.03537901]

       Close  Prediction
1526  129.75         NaN
1527  133.48         NaN
1528  131.98         NaN
1529  133.20         NaN
1530  126.70         NaN
1531  123.89         NaN
1532  122.88         NaN
1533  122.00         NaN
1534  121.99         NaN
1535  123.50         NaN
1536  123.02         NaN
1537  118.76         NaN
1538  114.22         NaN
1539  111.50         NaN
1540  117.98         NaN
1541  115.00         NaN
1542  115.24         NaN
1543  117.20         NaN
1544  112.67         NaN
1545  113.57         NaN
1546  111.50         NaN
1547  112.30         NaN
1548  115.91         NaN
15

In [32]:
#Load data testing
upload = files.upload()

Saving bitcoin_price_1week_Test - Test.csv to bitcoin_price_1week_Test - Test.csv


In [41]:
#Store the data into a variable
dfs = pd.read_csv('bitcoin_price_1week_Test - Test.csv')

#Show the first 7 rows of data
dfs.head(8)

Date     Open     High  ...    Close         Volume      Market Cap
0  Aug 07, 2017  3212.78  3397.68  ...  3378.94  1,482,280,000  52,987,300,000
1  Aug 06, 2017  3257.61  3293.29  ...  3213.94  1,105,030,000  53,720,900,000
2  Aug 05, 2017  2897.63  3290.01  ...  3252.91  1,945,700,000  47,778,200,000
3  Aug 04, 2017  2806.93  2899.33  ...  2895.89  1,002,120,000  46,276,200,000
4  Aug 03, 2017  2709.56  2813.31  ...  2804.73    804,797,000  44,666,400,000
5  Aug 02, 2017  2727.13  2762.53  ...  2710.67  1,094,950,000  44,950,800,000
6  Aug 01, 2017  2871.30  2921.35  ...  2718.26  1,324,670,000  47,321,800,000

[7 rows x 7 columns]

In [42]:
#remove the date column
dfs.drop(['Date'],1,inplace=True)
dfs.drop(['High'],1,inplace=True)
dfs.drop(['Low'],1,inplace=True)
dfs.drop(['Volume'],1,inplace=True)
dfs.drop(['Market Cap'],1,inplace=True)
dfs.drop(['Open'],1,inplace=True)
print(dfs.head(7))

     Close
0  3378.94
1  3213.94
2  3252.91
3  2895.89
4  2804.73
5  2710.67
6  2718.26


In [52]:
prediction_days_array = np.array(dfs['Close'])[:]
prediction_days_array = np.reshape(prediction_days_array, (7,1))
#Print the model predictions for the next 30 days
svm_prediction = svr_rbf.predict(prediction_days_array)

print(svm_prediction)

print()

#Print the actual price
print(dfs.head(7))

[1022.62211842 1038.12188657 1013.42150251 2065.07293436 2341.02624295
 2418.80350075 2420.264639  ]

     Close
0  3378.94
1  3213.94
2  3252.91
3  2895.89
4  2804.73
5  2710.67
6  2718.26
